<?php

namespace App\Core\Http;

use Illuminate\Http\Response;

class ApiResponse extends Response
{
    public array $data = [];
    public bool $status = true;
    public String $message = '';

    public function setStatusCode(int $code, ?string $text = null): static
    {
        if ($code < 200 || $code > 299) {
            $this->setStatus(false);
        }

        return parent::setStatusCode($code, $text); // TODO: Change the autogenerated stub
    }

    public function setMessage(String $message): static
    {
        $this->message = $message;
        $this->updateContent();

        return $this;
    }

    public function setStatus(bool $status): static
    {
        $this->status = $status;
        $this->updateContent();

        return $this;
    }

    public function set(String $key, mixed $value): static
    {
        $this->data[$key] = $value;
        $this->updateContent();
        return $this;
    }

    private function updateContent(): void
    {
        parent::setContent(array_merge($this->data, [
            'status' => $this->status,
            'message' => $this->message
        ]));
    }
}
